default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: 5
development:
  <<: *default
test:
  <<: *default
  url: <%= (ENV["DATABASE_URL"] || "").sub("_development","_test") %>