# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.3.0'

gem 'bootsnap', require: false
gem 'pg', '~> 1.5'
gem 'puma'
gem 'rack-attack'   # 任意（レート制限）
gem 'rack-cors'     # CORS有効化
gem 'rails', '~> 7.1'

group :development, :test do
  gem 'rspec-rails'
end

gem 'rubocop', '~> 1.80', group: :development

gem "ruby-lsp", "~> 0.26.1", :group => :development
