source "https://rubygems.org"
ruby "3.3.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma"
gem "rack-attack"   # 任意（レート制限）
gem "rack-cors"     # CORS有効化
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails"
end

